/**
 * レビュー判定ロジック
 * 
 * 機能:
 * - 星数に応じた自動送信/下書き保存の判定
 * - 星2以下のニュートラル通知文生成
 * - 低評価時の絵文字強制除去（安全弁）
 * - AI出力のノイズ除去
 * - 生成コスト削減のためのキャッシュ判定
 */

// --- 型定義 ---

/** 返信モード: 自動送信 or 手動（下書き保存） */
type ReplyMode = "auto" | "manual";

/** 星1〜5に対する返信設定マップ */
interface ReplyConfig {
    "1": ReplyMode;
    "2": ReplyMode;
    "3": ReplyMode;
    "4": ReplyMode;
    "5": ReplyMode;
}

/** 通知メッセージの出力 */
interface NotificationResult {
    /** 通知メッセージ本文 */
    message: string;
    /** 通知の種別（事実ベースか、トーン付きか） */
    type: "neutral" | "toned";
}

/** レビュー判定結果 */
interface ReviewActionResult {
    /** 自動送信か手動か */
    mode: ReplyMode;
    /** 通知メッセージ */
    notification: NotificationResult;
}

/** キャッシュ判定用の既存返信データ */
interface CachedReply {
    /** 元の口コミテキスト */
    originalReviewText: string;
    /** 生成済み返信文 */
    generatedReply: string;
    /** 生成時のタイムスタンプ（ISO文字列） */
    generatedAt: string;
}

/** キャッシュ有効期間（24時間 = 86400000ミリ秒） */
const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

// --- デフォルト設定 ---

/** デフォルトの返信設定（星3以上が自動、星1〜2が手動） */
const DEFAULT_REPLY_CONFIG: ReplyConfig = {
    "1": "manual",
    "2": "manual",
    "3": "auto",
    "4": "auto",
    "5": "auto",
};

// --- 絵文字除去の安全弁 ---

/**
 * Unicode絵文字を正規表現で検出・除去する
 * 対象: 一般的な絵文字範囲（Emoji_Presentation + Emoji_Modifier等）
 */
const EMOJI_REGEX = /[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{FE00}-\u{FE0F}\u{1F900}-\u{1F9FF}\u{1FA00}-\u{1FA6F}\u{1FA70}-\u{1FAFF}\u{200D}\u{20E3}\u{E0020}-\u{E007F}]/gu;

/**
 * 星2以下の返信文から絵文字を強制除去する
 * ビジネスルール: 低評価への返信に絵文字は不適切
 * 
 * @param text - AI生成の返信文
 * @param rating - 口コミの星数（1〜5）
 * @returns 絵文字除去後のテキスト
 */
export function sanitizeEmoji(text: string, rating: number): string {
    if (rating <= 2) {
        return text.replace(EMOJI_REGEX, "").replace(/\s{2,}/g, " ").trim();
    }
    return text;
}

// --- AI出力ノイズ除去 ---

/** AI が付加しがちな不要フレーズ一覧 */
const NOISE_PATTERNS: RegExp[] = [
    /AIで作成しました/g,
    /AI が生成しました/g,
    /この返信は自動生成です/g,
    /Generated by AI/gi,
    /This reply was generated/gi,
    /以上が返信です[。.]?/g,
    /以下が返信文です[。:]?/g,
    /返信文[:：]/g,
    /```[\s\S]*?```/g, // コードブロックの除去
];

/**
 * AI出力から不要なメタ情報・ノイズを除去する
 * 
 * @param text - AI生成の返信文
 * @param maxLength - 最大文字数（超過時は末尾を省略）
 * @returns 整形後のテキスト
 */
export function sanitizeAiOutput(text: string, maxLength: number = 500): string {
    let cleaned = text;

    // ノイズパターンを順次除去
    for (const pattern of NOISE_PATTERNS) {
        cleaned = cleaned.replace(pattern, "");
    }

    // 前後の空白・改行を整理
    cleaned = cleaned.replace(/\n{3,}/g, "\n\n").trim();

    // 文字数制限チェック
    if (cleaned.length > maxLength) {
        // 最後の句点・読点で切る
        const truncated = cleaned.substring(0, maxLength);
        const lastPeriod = Math.max(
            truncated.lastIndexOf("。"),
            truncated.lastIndexOf(".")
        );
        if (lastPeriod > maxLength * 0.5) {
            cleaned = truncated.substring(0, lastPeriod + 1);
        } else {
            cleaned = truncated + "…";
        }
    }

    return cleaned;
}

// --- 判定ロジック ---

/**
 * 星数に基づいて返信モード（自動/手動）を判定する
 * 
 * @param rating - 口コミの星数（1〜5）
 * @param config - ユーザーの返信設定（省略時はデフォルト）
 * @returns "auto" または "manual"
 */
export function getReplyMode(
    rating: number,
    config: ReplyConfig = DEFAULT_REPLY_CONFIG
): ReplyMode {
    const key = String(Math.min(5, Math.max(1, Math.round(rating)))) as keyof ReplyConfig;
    return config[key] ?? "manual";
}

/**
 * 通知メッセージを生成する
 * ビジネスルール: 星2以下は感情を排した事実ベース通知に固定
 * 
 * @param rating - 口コミの星数（1〜5）
 * @returns 通知結果（メッセージとタイプ）
 */
export function buildNotificationMessage(rating: number): NotificationResult {
    // 星2以下: ニュートラル通知（客観的事実のみ）
    if (rating <= 2) {
        return {
            message: `星${rating}つの投稿がありました`,
            type: "neutral",
        };
    }

    // 星3以上: トーンに応じた通知（ただし現時点では事実ベース）
    return {
        message: `星${rating}つの投稿がありました`,
        type: "toned",
    };
}

/**
 * レビューに対するアクション（判定＋通知）を統合的に処理する
 * 
 * @param rating - 口コミの星数
 * @param config - 返信設定
 * @returns 判定結果
 */
export function handleReviewAction(
    rating: number,
    config: ReplyConfig = DEFAULT_REPLY_CONFIG
): ReviewActionResult {
    return {
        mode: getReplyMode(rating, config),
        notification: buildNotificationMessage(rating),
    };
}

// --- キャッシュ判定 ---

/**
 * 既存のキャッシュが有効かどうかを判定する
 * 同じ口コミ内容に対して再生成を防ぎ、APIコストを削減する
 * 
 * @param currentReviewText - 現在の口コミテキスト
 * @param cached - キャッシュされた返信データ（存在しない場合は null）
 * @returns キャッシュが有効なら true
 */
export function isCacheValid(
    currentReviewText: string,
    cached: CachedReply | null
): boolean {
    if (!cached) return false;

    // 口コミの内容が変わっていないか確認
    if (cached.originalReviewText !== currentReviewText) return false;

    // TTL（有効期限）チェック
    const generatedTime = new Date(cached.generatedAt).getTime();
    const now = Date.now();
    if (now - generatedTime > CACHE_TTL_MS) return false;

    return true;
}

// --- 型のエクスポート ---
export type { ReplyConfig, ReplyMode, NotificationResult, ReviewActionResult, CachedReply };
