-- Reviews Table Schema
-- This file documents the structure of the 'reviews' table in Supabase.

-- Profiles table to store user subscription data
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  plan_status text default 'free', -- 'free' | 'active' | 'past_due' | 'canceled'
  plan_name text,
  billing_interval text, -- 'month' | 'year'

  constraint profiles_id_fkey foreign key (id) references auth.users (id)
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

create policy "Users can view their own profile"
  on public.profiles for select
  using ( auth.uid() = id );

create policy "Users can update their own profile"
  on public.profiles for update
  using ( auth.uid() = id );

-- Create a function to handle new user signups
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security modeller;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


create table public.reviews (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  user_id uuid references auth.users null, -- Added user_id for multi-tenant support
  author text null,
  rating integer null,
  text text null,           -- The content of the review
  source text null,         -- e.g. 'Google', 'HotPepper'
  status text null default 'unreplied'::text, -- 'unreplied' | 'replied'
  reply_content text null,  -- The generated/edited reply text
  date date null,           -- The date of the review itself
  google_review_id text unique null, -- Google's review ID (for deduplication)
  
  constraint reviews_pkey primary key (id)
);

-- RLS Policies for reviews
alter table public.reviews enable row level security;

create policy "Users can view their own reviews"
  on public.reviews for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own reviews"
  on public.reviews for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own reviews"
  on public.reviews for update
  using ( auth.uid() = user_id );
