-- Reviews Table Schema
-- This file documents the structure of the 'reviews' table in Supabase.

create table public.reviews (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  author text null,
  rating integer null,
  text text null,           -- The content of the review
  source text null,         -- e.g. 'Google', 'HotPepper'
  status text null default 'unreplied'::text, -- 'unreplied' | 'replied'
  reply_content text null,  -- The generated/edited reply text
  date date null,           -- The date of the review itself
  google_review_id text unique null, -- Google's review ID (for deduplication)
  
  constraint reviews_pkey primary key (id)
);

-- RLS Policies (Example)
-- alter table public.reviews enable row level security;
-- create policy "Enable read access for all users" on public.reviews for select using (true);
-- create policy "Enable insert for authenticated users only" on public.reviews for insert with check (auth.role() = 'authenticated');
