/**
 * レビュー判定ロジック
 * 
 * 機能:
 * - 星数に応じた自動送信/下書き保存の判定
 * - 星2以下のニュートラル通知文生成
 * - 低評価時の絵文字強制除去（安全弁）
 * - AI出力のノイズ除去
 * - 生成コスト削減のためのキャッシュ判定
 */

// --- 型定義 ---

/** 返信モード: 自動送信 or 手動（下書き保存） */
type ReplyMode = "auto" | "manual";

/** 星1〜5に対する返信設定マップ */
interface ReplyConfig {
    "1": ReplyMode;
    "2": ReplyMode;
    "3": ReplyMode;
    "4": ReplyMode;
    "5": ReplyMode;
}

/** 通知メッセージの出力 */
interface NotificationResult {
    /** 通知メッセージ本文 */
    message: string;
    /** 通知の種別（事実ベースか、トーン付きか） */
    type: "neutral" | "toned";
}

/** レビュー判定結果 */
interface ReviewActionResult {
    /** 自動送信か手動か */
    mode: ReplyMode;
    /** 通知メッセージ */
    notification: NotificationResult;
}

/** キャッシュ判定用の既存返信データ */
interface CachedReply {
    /** 元の口コミテキスト */
    originalReviewText: string;
    /** 生成済み返信文 */
    generatedReply: string;
    /** 生成時のタイムスタンプ（ISO文字列） */
    generatedAt: string;
}

/** キャッシュ有効期間（24時間 = 86400000ミリ秒） */
const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

// --- デフォルト設定 ---

/** デフォルトの返信設定（星3以上が自動、星1〜2が手動） */
const DEFAULT_REPLY_CONFIG: ReplyConfig = {
    "1": "manual",
    "2": "manual",
    "3": "auto",
    "4": "auto",
    "5": "auto",
};

// --- 絵文字除去の安全弁 ---

/**
 * Unicode絵文字を正規表現で検出・除去する
 * 対象: 一般的な絵文字範囲（Emoji_Presentation + Emoji_Modifier等）
 */
/**
 * Unicode絵文字を正規表現で検出・除去する
 * 対象: 一般的な絵文字範囲 + ZWJシーケンス
 */
const EMOJI_REGEX = /(\p{Emoji_Presentation}|\p{Emoji}\uFE0F)(\u200D(\p{Emoji_Presentation}|\p{Emoji}\uFE0F))*/gu;

/**
 * 星2以下の返信文から絵文字を制限する
 * ビジネスルール: 低評価への返信に絵文字は不適切（または最小限に留めるべき）
 * 
 * @param text - AI生成の返信文
 * @param rating - 口コミの星数（1〜5）
 * @returns 絵文字制限後のテキスト
 */
export function sanitizeEmoji(text: string, rating: number): string {
    if (rating <= 2) {
        // 絵文字（ZWJシーケンスを含む）を抽出
        // 🙇‍♂️ などの複雑な絵文字を一つの塊としてマッチさせる
        const emojiMatches = text.match(EMOJI_REGEX) || [];

        if (emojiMatches.length > 2) {
            // 3個目以降の絵文字を置換対象にする
            // 複雑な絵文字が途中で切れないよう、出現回数ベースで制御するルーター型置換
            let count = 0;
            return text.replace(EMOJI_REGEX, (match) => {
                count++;
                return count <= 2 ? match : "";
            }).replace(/\s{2,}/g, " ").trim();
        }
    }
    return text;
}

// --- AI出力ノイズ除去 ---

/** AI が付加しがちな不要フレーズ一覧 */
const NOISE_PATTERNS: RegExp[] = [
    /AIで作成しました/g,
    /AI が生成しました/g,
    /この返信は自動生成です/g,
    /Generated by AI/gi,
    /This reply was generated/gi,
    /以上が返信です[。.]?/g,
    /以下が返信文です[。:]?/g,
    /返信文[:：]/g,
    /```[\s\S]*?```/g, // コードブロックの除去
    /【感謝】/g,
    /【共感・謝罪】/g,
    /【個別対応】/g,
    /【再来店の促進】/g,
    /【.*?】/g, // その他の見出しも除去
];

/** 
 * Google 審査基準に基づく不適切語句チェック (NGワード)
 * 医療的効果、差別、攻撃的表現、虚偽の期待など
 */
const INAPPROPRIATE_WORDS = [
    "治る", "健康になる", "効く", // 医療的効果の誤認
    "絶対", "必ず", // 虚偽の保証
    "納得できない", "お客様の勘違い", // 攻撃的な反論
    "死", "殺", "バカ", "アホ", // 暴力・暴言
];

/**
 * AI出力から不要なメタ情報・ノイズを除去し、絵文字制限を適用する
 * 
 * @param text - AI生成の返信文
 * @param rating - 口コミの星数（絵文字制限用）
 * @param maxLength - 最大文字数（超過時は末尾を省略）
 * @returns 整形後のテキスト
 */
export function sanitizeAiOutput(text: string, rating?: number, maxLength: number = 500): string {
    let cleaned = text;

    // 不適切語句の検知と除去（安全弁）
    for (const word of INAPPROPRIATE_WORDS) {
        if (cleaned.includes(word)) {
            // 単純除去ではなく、審査に耐えうるよう安全なフレーズに置換、またはログ出力
            // 本来は再生成が望ましいが、ここでは簡易的に除去
            cleaned = cleaned.split(word).join("");
        }
    }

    // 絵文字制限の適用
    if (rating !== undefined) {
        cleaned = sanitizeEmoji(cleaned, rating);
    }

    // ノイズパターンを順次除去
    for (const pattern of NOISE_PATTERNS) {
        cleaned = cleaned.replace(pattern, "");
    }

    // 前後の空白・改行を整理
    cleaned = cleaned.replace(/\n{3,}/g, "\n\n").trim();

    // 文字数制限チェック
    if (cleaned.length > maxLength) {
        // 最後の句点・読点で切る
        const truncated = cleaned.substring(0, maxLength);
        const lastPeriod = Math.max(
            truncated.lastIndexOf("。"),
            truncated.lastIndexOf(".")
        );
        if (lastPeriod > maxLength * 0.5) {
            cleaned = truncated.substring(0, lastPeriod + 1);
        } else {
            cleaned = truncated + "…";
        }
    }

    return cleaned;
}

// --- 判定ロジック ---

/**
 * 星数に基づいて返信モード（自動/手動）を判定する
 * 
 * @param rating - 口コミの星数（1〜5）
 * @param config - ユーザーの返信設定（省略時はデフォルト）
 * @returns "auto" または "manual"
 */
export function getReplyMode(
    rating: number,
    config: ReplyConfig = DEFAULT_REPLY_CONFIG
): ReplyMode {
    const key = String(Math.min(5, Math.max(1, Math.round(rating)))) as keyof ReplyConfig;
    return config[key] ?? "manual";
}

/**
 * 通知メッセージを生成する
 * ビジネスルール: 星2以下は感情を排した事実ベース通知に固定
 * 
 * @param rating - 口コミの星数（1〜5）
 * @returns 通知結果（メッセージとタイプ）
 */
export function buildNotificationMessage(rating: number): NotificationResult {
    // 星2以下: ニュートラル通知（客観的事実のみ）
    if (rating <= 2) {
        return {
            message: `星${rating}つの投稿がありました`,
            type: "neutral",
        };
    }

    // 星3以上: トーンに応じた通知（ただし現時点では事実ベース）
    return {
        message: `星${rating}つの投稿がありました`,
        type: "toned",
    };
}

/**
 * レビューに対するアクション（判定＋通知）を統合的に処理する
 * 
 * @param rating - 口コミの星数
 * @param config - 返信設定
 * @returns 判定結果
 */
export function handleReviewAction(
    rating: number,
    config: ReplyConfig = DEFAULT_REPLY_CONFIG
): ReviewActionResult {
    return {
        mode: getReplyMode(rating, config),
        notification: buildNotificationMessage(rating),
    };
}

// --- キャッシュ判定 ---

/**
 * 既存のキャッシュが有効かどうかを判定する
 * 同じ口コミ内容に対して再生成を防ぎ、APIコストを削減する
 * 
 * @param currentReviewText - 現在の口コミテキスト
 * @param cached - キャッシュされた返信データ（存在しない場合は null）
 * @returns キャッシュが有効なら true
 */
export function isCacheValid(
    currentReviewText: string,
    cached: CachedReply | null
): boolean {
    if (!cached) return false;

    // 口コミの内容が変わっていないか確認
    if (cached.originalReviewText !== currentReviewText) return false;

    // TTL（有効期限）チェック
    const generatedTime = new Date(cached.generatedAt).getTime();
    const now = Date.now();
    if (now - generatedTime > CACHE_TTL_MS) return false;

    return true;
}

// --- 型のエクスポート ---
export type { ReplyConfig, ReplyMode, NotificationResult, ReviewActionResult, CachedReply };
